[project]
name = "python-course-homework-assignments"
version = "0.0.1"
requires-python = ">=3.14.2"
authors = [
  {name = "Roman Chechevatov", email = "334869@niuitmo.ru"}
]
dependencies = [
    "click",
]
