[project]
name = "python-course-homework-assignments-4438cfe6-9036-4c32-b279-ff960332732a"
version = "0.0.2"
requires-python = ">=3.14.2"
authors = [
  {name = "Roman Chechevatov", email = "334869@niuitmo.ru"}
]
dependencies = []
